# Generated by Django 3.1.4 on 2020-12-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default='')),
                ('expire_date', models.DateField(default='')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', models.ImageField(default='', upload_to='icons')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='SponsorContent',
            fields=[
                ('ad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ad')),
                ('sponsor_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SponsorContent',
                'verbose_name_plural': 'SponsorContents',
            },
            bases=('core.ad',),
        ),
        migrations.CreateModel(
            name='AdVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('videoUrl', models.CharField(default='', max_length=1500)),
                ('thumbnailUrl', models.CharField(blank=True, default='', max_length=1500, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ad')),
            ],
            options={
                'verbose_name': 'AdVideo',
                'verbose_name_plural': 'AdVideos',
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ad')),
            ],
            options={
                'verbose_name': 'AdImage',
                'verbose_name_plural': 'AdImages',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='regions',
            field=models.ManyToManyField(to='core.City'),
        ),
    ]
