# Generated by Django 3.1.4 on 2020-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201212_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
