# Generated by Django 3.1.4 on 2020-12-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201212_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(default='', upload_to='icons'),
        ),
    ]
