# Generated by Django 3.1.4 on 2020-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201213_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_whatsapp_number',
            field=models.BooleanField(default=False),
        ),
    ]
