# Generated by Django 3.1.4 on 2020-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ad_is_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
