# Generated by Django 3.1.4 on 2020-12-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ad_is_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Акция')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateField(default='', verbose_name='Активен до')),
                ('regions', models.ManyToManyField(to='core.City', verbose_name='Регион')),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='expire_date',
            field=models.DateField(default='', verbose_name='Активен до'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_share',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_whatsapp_number',
            field=models.BooleanField(default=False, verbose_name='Whatsapp номер'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='regions',
            field=models.ManyToManyField(to='core.City', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('videoUrl', models.CharField(default='', max_length=1500)),
                ('thumbnailUrl', models.CharField(blank=True, default='', max_length=1500, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
            ],
            options={
                'verbose_name': 'AdVideo',
                'verbose_name_plural': 'AdVideos',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
            ],
        ),
    ]
