# Generated by Django 3.1.4 on 2020-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201224_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'AdImage', 'verbose_name_plural': 'AdImages'},
        ),
        migrations.AlterModelOptions(
            name='sponsorcontent',
            options={'verbose_name': 'Спонсорский контент', 'verbose_name_plural': 'Спонсорские контенты'},
        ),
        migrations.AddField(
            model_name='sponsorcontent',
            name='redirect_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Новость'),
        ),
    ]
