# Generated by Django 3.1.4 on 2020-12-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201226_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('icon', models.FileField(default='', upload_to='icons')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('is_whatsapp_number', models.BooleanField(default=False, verbose_name='Whatsapp номер')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infocategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
                'ordering': ['category'],
            },
        ),
    ]
