# Generated by Django 3.1.4 on 2020-12-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_info_infocategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['category'], 'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Реклама (категория)', 'verbose_name_plural': 'Рекламы (категории)'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['category'], 'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
        migrations.AlterModelOptions(
            name='infocategory',
            options={'verbose_name': 'Информация (категория)', 'verbose_name_plural': 'Информации (категории)'},
        ),
    ]
