# Generated by Django 3.1.4 on 2020-12-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201226_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
