# Generated by Django 3.1.4 on 2020-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Sub title'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Title'),
        ),
    ]
