# Generated by Django 3.1.4 on 2020-12-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201226_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(default='', max_length=350),
        ),
    ]
